/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eBatcher7984Sol from "./eBatcher7984.sol";
export type { eBatcher7984Sol };
export type { EToken7984 } from "./EToken7984";
