/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eBatcherSol from "./eBatcher.sol";
export type { eBatcherSol };
export type { EToken } from "./EToken";
